#!/usr/bin/env bash

target=$1

os="`cat /etc/os-release | grep -E '^ID=' | awk -F '=' '{ print $2 }'`"
. ~/dotfiles/scripts/functions.sh


####################################################################################################
##                                            Arch                                                ##
####################################################################################################
function arch () {
	if ! which yay 2>&1 > /dev/null; then
		sudo pacman -S --needed git base-devel
		git clone https://aur.archlinux.org/yay.git ./gits/yay
		pushd ./gits/yay
		makepkg -si
		popd
	fi

	install git git-delta lazygit
	install glab github-cli
	install less man zoxide fzf
	install neovim mise
	yay -Sy --noconfirm jqp-bin

	#
	# Pyhton
	#
	install pyenv python-pdm python-pip uv

	#
	# JS/TS
	#
	install nvm

	#
	# Go
	#
	install go

	#
	# Rust
	#
	install rustup

	#
	# Fonts
	#
	install noto-fonts-cjk nerd-fonts > /dev/null
	yay -Sy --noconfirm ttf-mplus-git

	if [[ $target == 'desktop' ]]; then
		echo "----------------------------------------------------------------------------------------------------\nbla";
		install cmake meson cpio pkg-config git gcc
		install hyprland wofi
		install waybar cava
		install mako
		install uwsm libnewt ly
		install pipewire pipewire-session-manager pipewire-alsa pipewire-audio pipewire-jack pipewire-pulse wireplumber 
		install lib32-libpipewire libpipewire libwireplumber
		# sudo yay -Sy --noconfirm xdg-desktop-portal-wayland
		install pipewire-libcamera 
		install grim slurp
		install qt5-wayland qt6-wayland

		# Enable file indexing
		balooctl6 enable

		systemctl enable ly.service > /dev/null
		systemctl disable getty@tty2.service > /dev/null
		systemctl disable DISPLAY_MANAGER 2>&1 > /dev/null
	fi

}

####################################################################################################
##                                          Ubunutu                                               ##
####################################################################################################
function unbuntu() {
	[ ! -d ./gits/glab.deb ] && wget -O ./gits/glab.deb https://gitlab.com/gitlab-org/cli/-/releases/v1.59.2/downloads/glab_1.59.2_linux_amd64.deb
	sudo dpkg -i ./gits/glab.deb

	[ ! -d ./gits/delta.deb ] && wget -O ./gits/delta.deb https://github.com/dandavison/delta/releases/download/0.18.2/git-delta_0.18.2_amd64.deb
	sudo dpkg -i ./gits/delta.deb

	[ ! -d ./gits/zoxide.deb ] && wget -O ./gits/zoxide.deb https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.8/zoxide_0.9.8-1_amd64.deb
	sudo dpkg -i ./gits/zoxide.deb

	which cargo > /dev/null 2>&1
	if [[ ! $? = 0 ]]; then
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	fi

	[ ! -d ./gits/go.tar.gz ] && wget -O ./gits/go.tar.gz https://go.dev/dl/go1.24.4.linux-amd64.tar.gz
	sudo rm -rf /usr/local/go
	sudo tar -C /usr/local -xzf ./gits/go.tar.gz
	if [[ ! ":$PATH:" == *"/usr/local/go/bin"* ]]; then
		echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.zprofile
	fi

	/usr/local/go/bin/go install github.com/jesseduffield/lazygit@latest

	[ ! -d ~/.fzf ] && git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install  --no-key-bindings --no-completion --no-update-rc

	curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz -O ./gits/nvim-linux.tar.gz/
	sudo rm -rf /opt/nvim
	sudo tar -C /opt -xzf ./gits/nvim-linux.tar.gz

	if ! type rustup; then
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	fi

	# @TODO: install pyenv
}



####################################################################################################
##                                          Install                                               ##
####################################################################################################

upgrade 2>&1 > /dev/null

case $os in
	arch)
		arch
		;;
	ubuntu)
		unbuntu
		;;
esac

install stow zip unzip ripgrep bat tmux zsh jq clang chafa
install eza

curl -s https://ohmyposh.dev/install.sh | bash -s
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

[ ! -d ~/.tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

sudo localectl set-locale LC_TIME=ja_JP.UTF-8
mkdir -p .zfunc

