#!/usr/bin/env python

import sys
import json


def main():
	data = {}

	input = sys.stdin.read()

	lines = input.split('\n')

	tooltip = date = ""
	if len(lines) > 0:
		date = lines[0].strip()
	if len(lines) > 1:
		tooltip = lines[1:]

	data['text'] = date
	data['tooltip'] = '\n'.join(tooltip)


	print(json.dumps(data))

if __name__ == '__main__':
	main()





